server:
  port: 8181
  servlet:
    context-path: /api
  shutdown: graceful
http2:
  port: 8182
http3:
  port: 8183

spring:
  profiles:
    active: ${APP_PROFILE:dev}
  #  webflux:
  #    base-path: /api
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:sonartestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;IFEXISTS=FALSE}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password12@}
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 300000
    connection-timeout: 20000
    max-lifetime: 1200000
    connection-test-query: SELECT 1
    pool-name: H2HikariPool
    auto-commit: true
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 25
          fetch_size: 100
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#        region:
#            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
#      javax:
#        cache:
#          provider: org.ehcache.jsr107.EhcacheCachingProvider
#          uri: ehcache.xml
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  http:
    converters:
      preferred-json-mapper: jackson2

#  jackson:
#    property-naming-strategy: SNAKE_CASE
#    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      write-dates-as-timestamps: false
#      indent-output: true
#    default-property-inclusion: non_null

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    org.springframework.cache: TRACE

security:
  password:
    algorithm: HmacSHA512
    key: EPAM